apiVersion: v1
kind: Config
clusters:
  - cluster:
      insecure-skip-tls-verify: true
      server: {{.URL}}
    name: minkapi-{{.Name}}
contexts:
  - context:
      cluster: minkapi-{{.Name}}
      user: minkapi-user
      namespace: default
    name: minkapi-{{.Name}}
current-context: minkapi-{{.Name}}
users:
  - name: minkapi-user
    user: {}
