apiVersion: sa.gardener.cloud/v1alpha1
kind: ScalingConstraint
metadata:
  name: example
  namespace: default
spec:
  nodePools:
    - name: small
      region: eu-west-1
      priority: 0
      availabilityZones:
        - eu-west-1b
      labels:
        kubernetes.io/arch: amd64
        worker.gardener.cloud/pool: small
        worker.gardener.cloud/cri-name: containerd
        worker.gardener.cloud/system-components: "true"
      quota:
        cpu: "32"
        memory: 128Gi
      nodeTemplates:
        - name: m5l
          instanceType: m5.large
          architecture: amd64
          priority: 0
          maxVolumes: 25
          capacity:
            cpu: "2"
            memory: 8Gi
            gpu: "0"
            pods: "110"
          kubeReservedCapacity:
            cpu: 80m
            memory: 1Gi
            pid: 20k
          systemReservedCapacity:
            cpu: 20m
            memory: 256Mi