apiVersion: config.sa.gardener.cloud/v1alpha1
kind: OperatorConfig
controlPlaneClientConnection:
  kubeConfigPath: ./operator/scenarios/controlPlaneKubeconfig.yaml
dataPlaneClientConnection:
  kubeConfigPath: ./operator/scenarios/dataPlaneKubeconfig.yaml
controllers:
  scalingAdvice:
    requeueAfter: 10s
